/**
 * Shared Dota 2 hero roster (Valve numeric ids). Used by lobby.html + counterPickLobby.html.
 * tags = offensive/toolkit strengths; weakness = vulnerability keys for counter-pick matching.
 * Generated by scripts/build-heroes-data.mjs — re-run after editing that script.
 */
export const TAG_LABELS = {
  gap_close: "Gap closer",
  silence: "Silence",
  mana_burn: "Mana burn / burn",
  magic_resist: "Magic resist / shield",
  magic_reflect: "Reflect / return magic",
  magic_damage: "Magic damage",
  magic_burst: "Magic burst",
  physical_burst: "Physical burst",
  physical_right_click: "Right-click carry",
  pure_damage: "Pure / mixed damage",
  break: "Break / passive disable",
  disable: "Hard disable",
  lockdown: "Long lockdown",
  long_lockdown: "Long lockdown",
  root: "Roots",
  save_escape: "Save / escape",
  save_heal: "Save / heal",
  vision_control: "Vision",
  vision_true: "True sight",
  dust_true_strike: "Reveal / true strike",
  tank_initiation: "Initiation tank",
  tank_frontline: "Frontline tank",
  farm_scale: "Late-game scale",
  split_push: "Split push",
  global_pressure: "Global pressure",
  mobility: "Mobility",
  kite: "Kite susceptible",
  early_pressure: "Early pressure weak",
  gank: "Gank vulnerable",
  aoe_control: "AoE control",
  cleave: "Cleave / illusions",
  miss_chance: "Evasion / miss",
  point_target_disable: "Single-target disable",
  flex_toolkit: "Flexible toolkit",
  armor_reduction: "Armor reduction weak",
};

/** @param {{ tags?: string[], weakness?: string[], positions?: number[], attr?: string, cx?: number }} hero */
export function heroTagTooltipLines(hero) {
  const lines = [];
  const tagStr = (hero.tags || []).map((k) => TAG_LABELS[k] || k).join(", ");
  const weakStr = (hero.weakness || []).map((k) => TAG_LABELS[k] || k).join(", ");
  if (tagStr) lines.push("Strengths: " + tagStr);
  if (weakStr) lines.push("Weak to: " + weakStr);
  lines.push(`Pos: ${(hero.positions || []).join(", ")}`);
  lines.push(`${hero.attr?.toUpperCase() || "?"} · Complexity ${hero.cx || "?"}`);
  return lines;
}

/**
 * Pool hero ids that counter every enemy: for each enemy, at least one of enemy.weakness keys
 * must appear in candidate.tags (same vocabulary).
 */
export function getCounterHeroIdsFromTags(enemyHeroIds, poolHeroIds, roster = HEROES) {
  const byId = new Map(roster.map((h) => [h.id, h]));
  const enemies = (enemyHeroIds || []).map((id) => byId.get(id)).filter(Boolean);
  if (!enemies.length) return new Set();
  const pool = (poolHeroIds || []).map((id) => byId.get(id)).filter(Boolean);
  const out = new Set();
  for (const h of pool) {
    const hTags = new Set(h.tags || []);
    let ok = true;
    for (const e of enemies) {
      const ws = e.weakness || [];
      if (!ws.length) continue;
      const hit = ws.some((w) => hTags.has(w));
      if (!hit) {
        ok = false;
        break;
      }
    }
    if (ok) out.add(h.id);
  }
  return out;
}

export const HEROES = [
  {
    "id": 1,
    "name": "Anti-Mage",
    "imgName": "antimage",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "gap_close",
      "mana_burn",
      "magic_resist",
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "lockdown",
      "early_pressure",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 2,
    "name": "Axe",
    "imgName": "axe",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 3,
    "name": "Bane",
    "imgName": "bane",
    "positions": [
      4,
      5
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 4,
    "name": "Bloodseeker",
    "imgName": "bloodseeker",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 5,
    "name": "Crystal Maiden",
    "imgName": "crystal_maiden",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 6,
    "name": "Drow Ranger",
    "imgName": "drow_ranger",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 7,
    "name": "Earthshaker",
    "imgName": "earthshaker",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "silence",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 8,
    "name": "Juggernaut",
    "imgName": "juggernaut",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 9,
    "name": "Mirana",
    "imgName": "mirana",
    "positions": [
      2,
      4
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 10,
    "name": "Morphling",
    "imgName": "morphling",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 3,
    "tags": [
      "magic_damage",
      "save_escape",
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage",
      "pure_damage"
    ],
    "weakness": [
      "silence",
      "mana_burn",
      "long_lockdown",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 11,
    "name": "Shadow Fiend",
    "imgName": "nevermore",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage",
      "magic_resist"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 12,
    "name": "Phantom Lancer",
    "imgName": "phantom_lancer",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 13,
    "name": "Puck",
    "imgName": "puck",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "gank",
      "dust_true_strike"
    ]
  },
  {
    "id": 14,
    "name": "Pudge",
    "imgName": "pudge",
    "positions": [
      1,
      4
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "magic_resist",
      "disable",
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "kite",
      "mana_burn",
      "armor_reduction",
      "silence",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 15,
    "name": "Razor",
    "imgName": "razor",
    "positions": [
      1,
      3
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "physical_damage",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage",
      "point_target_disable"
    ]
  },
  {
    "id": 16,
    "name": "Sand King",
    "imgName": "sand_king",
    "positions": [
      3,
      4
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "flex_toolkit"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 17,
    "name": "Storm Spirit",
    "imgName": "storm_spirit",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 18,
    "name": "Sven",
    "imgName": "sven",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 19,
    "name": "Tiny",
    "imgName": "tiny",
    "positions": [
      2,
      4
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 20,
    "name": "Vengeful Spirit",
    "imgName": "vengefulspirit",
    "positions": [
      4,
      5
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 21,
    "name": "Windranger",
    "imgName": "windrunner",
    "positions": [
      2,
      4
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 22,
    "name": "Zeus",
    "imgName": "zuus",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 23,
    "name": "Kunkka",
    "imgName": "kunkka",
    "positions": [
      2,
      3
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 25,
    "name": "Lina",
    "imgName": "lina",
    "positions": [
      1,
      2
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "magic_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank"
    ]
  },
  {
    "id": 26,
    "name": "Lion",
    "imgName": "lion",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 27,
    "name": "Shadow Shaman",
    "imgName": "shadow_shaman",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 28,
    "name": "Slardar",
    "imgName": "slardar",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 29,
    "name": "Tidehunter",
    "imgName": "tidehunter",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 30,
    "name": "Witch Doctor",
    "imgName": "witch_doctor",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 31,
    "name": "Lich",
    "imgName": "lich",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "gap_close"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 32,
    "name": "Riki",
    "imgName": "riki",
    "positions": [
      1,
      4
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 33,
    "name": "Enigma",
    "imgName": "enigma",
    "positions": [
      3,
      4
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "flex_toolkit"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 34,
    "name": "Tinker",
    "imgName": "tinker",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "magic_burst",
      "global_pressure",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "magic_resist"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "gank",
      "dust_true_strike"
    ]
  },
  {
    "id": 35,
    "name": "Sniper",
    "imgName": "sniper",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 36,
    "name": "Necrophos",
    "imgName": "necrolyte",
    "positions": [
      2,
      3
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "magic_damage",
      "mana_burn",
      "pure_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close"
    ]
  },
  {
    "id": 37,
    "name": "Warlock",
    "imgName": "warlock",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 38,
    "name": "Beastmaster",
    "imgName": "beastmaster",
    "positions": [
      3,
      4
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "flex_toolkit",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 39,
    "name": "Queen of Pain",
    "imgName": "queenofpain",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 40,
    "name": "Venomancer",
    "imgName": "venomancer",
    "positions": [
      3,
      4
    ],
    "attr": "uni",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "flex_toolkit"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 41,
    "name": "Faceless Void",
    "imgName": "faceless_void",
    "positions": [
      1,
      3
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "save_escape",
      "chrono",
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "mana_burn",
      "silence",
      "gap_close",
      "armor_reduction",
      "kite",
      "pure_damage",
      "point_target_disable"
    ]
  },
  {
    "id": 42,
    "name": "Wraith King",
    "imgName": "skeleton_king",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "magic_resist"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 43,
    "name": "Death Prophet",
    "imgName": "death_prophet",
    "positions": [
      2,
      3
    ],
    "attr": "uni",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "burst_magic"
    ]
  },
  {
    "id": 44,
    "name": "Phantom Assassin",
    "imgName": "phantom_assassin",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_burst",
      "gap_close",
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "magic_damage",
      "miss_chance",
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 45,
    "name": "Pugna",
    "imgName": "pugna",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "gap_close",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 46,
    "name": "Templar Assassin",
    "imgName": "templar_assassin",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 47,
    "name": "Viper",
    "imgName": "viper",
    "positions": [
      2,
      3
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "physical_damage",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "point_target_disable"
    ]
  },
  {
    "id": 48,
    "name": "Luna",
    "imgName": "luna",
    "positions": [
      1,
      4
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 49,
    "name": "Dragon Knight",
    "imgName": "dragon_knight",
    "positions": [
      2,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 50,
    "name": "Dazzle",
    "imgName": "dazzle",
    "positions": [
      2,
      5
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 51,
    "name": "Clockwerk",
    "imgName": "rattletrap",
    "positions": [
      4,
      5
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 52,
    "name": "Leshrac",
    "imgName": "leshrac",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 53,
    "name": "Nature's Prophet",
    "imgName": "furion",
    "positions": [
      4,
      5
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 54,
    "name": "Lifestealer",
    "imgName": "life_stealer",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close",
      "magic_resist"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 55,
    "name": "Dark Seer",
    "imgName": "dark_seer",
    "positions": [
      3,
      4
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "magic_damage"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 56,
    "name": "Clinkz",
    "imgName": "clinkz",
    "positions": [
      1,
      4
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 57,
    "name": "Omniknight",
    "imgName": "omniknight",
    "positions": [
      3,
      5
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "magic_resist"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 58,
    "name": "Enchantress",
    "imgName": "enchantress",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 59,
    "name": "Huskar",
    "imgName": "huskar",
    "positions": [
      1,
      2
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "magic_damage",
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "tank_frontline",
      "magic_resist",
      "pure_damage"
    ],
    "weakness": [
      "pure_damage",
      "break",
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 60,
    "name": "Night Stalker",
    "imgName": "night_stalker",
    "positions": [
      2,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 61,
    "name": "Broodmother",
    "imgName": "broodmother",
    "positions": [
      2,
      3
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "point_target_disable"
    ]
  },
  {
    "id": 62,
    "name": "Bounty Hunter",
    "imgName": "bounty_hunter",
    "positions": [
      3,
      4
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "physical_damage"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 63,
    "name": "Weaver",
    "imgName": "weaver",
    "positions": [
      1,
      4
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 64,
    "name": "Jakiro",
    "imgName": "jakiro",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 65,
    "name": "Batrider",
    "imgName": "batrider",
    "positions": [
      2,
      3
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "flex_toolkit",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "burst_magic"
    ]
  },
  {
    "id": 66,
    "name": "Chen",
    "imgName": "chen",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 67,
    "name": "Spectre",
    "imgName": "spectre",
    "positions": [
      1,
      3
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage",
      "point_target_disable"
    ]
  },
  {
    "id": 68,
    "name": "Ancient Apparition",
    "imgName": "ancient_apparition",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 69,
    "name": "Doom",
    "imgName": "doom_bringer",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close",
      "pure_damage"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 70,
    "name": "Ursa",
    "imgName": "ursa",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage",
      "magic_resist"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 71,
    "name": "Spirit Breaker",
    "imgName": "spirit_breaker",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 72,
    "name": "Gyrocopter",
    "imgName": "gyrocopter",
    "positions": [
      1,
      4
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 73,
    "name": "Alchemist",
    "imgName": "alchemist",
    "positions": [
      1,
      2
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "tank_frontline"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 74,
    "name": "Invoker",
    "imgName": "invoker",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "magic_burst",
      "disable",
      "mobility",
      "save_heal",
      "vision_control",
      "magic_damage",
      "mana_burn"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "gank",
      "dust_true_strike"
    ]
  },
  {
    "id": 75,
    "name": "Silencer",
    "imgName": "silencer",
    "positions": [
      2,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 76,
    "name": "Outworld Destroyer",
    "imgName": "obsidian_destroyer",
    "positions": [
      1,
      2
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "mana_burn",
      "magic_burst",
      "physical_right_click",
      "farm_scale",
      "mobility",
      "magic_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "armor_reduction",
      "gank"
    ]
  },
  {
    "id": 77,
    "name": "Lycan",
    "imgName": "lycan",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 78,
    "name": "Brewmaster",
    "imgName": "brewmaster",
    "positions": [
      2,
      3
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "flex_toolkit",
      "magic_resist"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "burst_magic"
    ]
  },
  {
    "id": 79,
    "name": "Shadow Demon",
    "imgName": "shadow_demon",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 80,
    "name": "Lone Druid",
    "imgName": "lone_druid",
    "positions": [
      1,
      3
    ],
    "attr": "agi",
    "cx": 3,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage",
      "point_target_disable"
    ]
  },
  {
    "id": 81,
    "name": "Chaos Knight",
    "imgName": "chaos_knight",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 82,
    "name": "Meepo",
    "imgName": "meepo",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 3,
    "tags": [
      "physical_right_click",
      "split_push",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "aoe_control",
      "silence",
      "cleave",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 83,
    "name": "Treant Protector",
    "imgName": "treant",
    "positions": [
      4,
      5
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 84,
    "name": "Ogre Magi",
    "imgName": "ogre_magi",
    "positions": [
      3,
      5
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 85,
    "name": "Undying",
    "imgName": "undying",
    "positions": [
      4,
      5
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "tank_frontline",
      "magic_resist",
      "pure_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 86,
    "name": "Rubick",
    "imgName": "rubick",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "magic_reflect"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 87,
    "name": "Disruptor",
    "imgName": "disruptor",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 88,
    "name": "Nyx Assassin",
    "imgName": "nyx_assassin",
    "positions": [
      2,
      4
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 89,
    "name": "Naga Siren",
    "imgName": "naga_siren",
    "positions": [
      1,
      4
    ],
    "attr": "agi",
    "cx": 3,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 90,
    "name": "Keeper of the Light",
    "imgName": "keeper_of_the_light",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 91,
    "name": "Io",
    "imgName": "wisp",
    "positions": [
      4,
      5
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "save_heal",
      "relocate",
      "vision_control",
      "disable",
      "flex_toolkit",
      "mana_burn"
    ],
    "weakness": [
      "silence",
      "burst_magic",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 92,
    "name": "Visage",
    "imgName": "visage",
    "positions": [
      2,
      3
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "burst_magic"
    ]
  },
  {
    "id": 93,
    "name": "Slark",
    "imgName": "slark",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 94,
    "name": "Medusa",
    "imgName": "medusa",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "magic_resist",
      "split_shot",
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "mana_burn",
      "pure_damage",
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 95,
    "name": "Troll Warlord",
    "imgName": "troll_warlord",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 96,
    "name": "Centaur Warrunner",
    "imgName": "centaur",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 97,
    "name": "Magnus",
    "imgName": "magnataur",
    "positions": [
      2,
      3
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "flex_toolkit",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "burst_magic"
    ]
  },
  {
    "id": 98,
    "name": "Timbersaw",
    "imgName": "shredder",
    "positions": [
      2,
      3
    ],
    "attr": "str",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "mana_burn",
      "pure_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 99,
    "name": "Bristleback",
    "imgName": "bristleback",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 100,
    "name": "Tusk",
    "imgName": "tusk",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 101,
    "name": "Skywrath Mage",
    "imgName": "skywrath_mage",
    "positions": [
      2,
      4
    ],
    "attr": "int",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike"
    ]
  },
  {
    "id": 102,
    "name": "Abaddon",
    "imgName": "abaddon",
    "positions": [
      3,
      5
    ],
    "attr": "uni",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "flex_toolkit",
      "magic_resist"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 103,
    "name": "Elder Titan",
    "imgName": "elder_titan",
    "positions": [
      4,
      5
    ],
    "attr": "str",
    "cx": 3,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "tank_frontline"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 104,
    "name": "Legion Commander",
    "imgName": "legion_commander",
    "positions": [
      1,
      3
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 105,
    "name": "Techies",
    "imgName": "techies",
    "positions": [
      2,
      4
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit",
      "silence"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 106,
    "name": "Ember Spirit",
    "imgName": "ember_spirit",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "physical_right_click",
      "farm_scale",
      "physical_damage",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "root",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 107,
    "name": "Earth Spirit",
    "imgName": "earth_spirit",
    "positions": [
      2,
      4
    ],
    "attr": "str",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "mana_burn",
      "kite"
    ]
  },
  {
    "id": 108,
    "name": "Underlord",
    "imgName": "abyssal_underlord",
    "positions": [
      3,
      5
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline",
      "gap_close",
      "magic_resist",
      "pure_damage"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 109,
    "name": "Terrorblade",
    "imgName": "terrorblade",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 110,
    "name": "Phoenix",
    "imgName": "phoenix",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 3,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 111,
    "name": "Oracle",
    "imgName": "oracle",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 3,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence",
      "mana_burn"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 112,
    "name": "Winter Wyvern",
    "imgName": "winter_wyvern",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 113,
    "name": "Arc Warden",
    "imgName": "arc_warden",
    "positions": [
      1,
      2
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "burst_magic"
    ]
  },
  {
    "id": 114,
    "name": "Monkey King",
    "imgName": "monkey_king",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "gap_close",
      "physical_burst",
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "true_strike",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  },
  {
    "id": 119,
    "name": "Dark Willow",
    "imgName": "dark_willow",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 120,
    "name": "Pangolier",
    "imgName": "pangolier",
    "positions": [
      2,
      3
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "flex_toolkit",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage",
      "burst_magic"
    ]
  },
  {
    "id": 121,
    "name": "Grimstroke",
    "imgName": "grimstroke",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 123,
    "name": "Hoodwink",
    "imgName": "hoodwink",
    "positions": [
      2,
      4
    ],
    "attr": "agi",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "physical_damage"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "point_target_disable"
    ]
  },
  {
    "id": 126,
    "name": "Void Spirit",
    "imgName": "void_spirit",
    "positions": [
      2,
      4
    ],
    "attr": "uni",
    "cx": 3,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 128,
    "name": "Snapfire",
    "imgName": "snapfire",
    "positions": [
      2,
      4
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "save_heal",
      "vision_control",
      "disable",
      "flex_toolkit"
    ],
    "weakness": [
      "silence",
      "gank",
      "gap_close",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 129,
    "name": "Mars",
    "imgName": "mars",
    "positions": [
      2,
      3
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 131,
    "name": "Ringmaster",
    "imgName": "ringmaster",
    "positions": [
      4,
      5
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "save_heal",
      "vision_control",
      "disable",
      "magic_damage",
      "silence"
    ],
    "weakness": [
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 135,
    "name": "Dawnbreaker",
    "imgName": "dawnbreaker",
    "positions": [
      3,
      4
    ],
    "attr": "str",
    "cx": 2,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "tank_frontline"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike"
    ]
  },
  {
    "id": 136,
    "name": "Marci",
    "imgName": "marci",
    "positions": [
      3,
      4
    ],
    "attr": "uni",
    "cx": 2,
    "tags": [
      "tank_initiation",
      "disable",
      "save_heal",
      "vision_control",
      "flex_toolkit"
    ],
    "weakness": [
      "mana_burn",
      "kite",
      "pure_damage",
      "gap_close",
      "silence",
      "dust_true_strike",
      "burst_magic"
    ]
  },
  {
    "id": 137,
    "name": "Primal Beast",
    "imgName": "primal_beast",
    "positions": [
      2,
      3
    ],
    "attr": "str",
    "cx": 1,
    "tags": [
      "magic_burst",
      "mobility",
      "tank_initiation",
      "disable",
      "tank_frontline",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gank",
      "mana_burn",
      "kite",
      "pure_damage"
    ]
  },
  {
    "id": 138,
    "name": "Muerta",
    "imgName": "muerta",
    "positions": [
      1,
      2
    ],
    "attr": "int",
    "cx": 2,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "magic_damage"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank"
    ]
  },
  {
    "id": 145,
    "name": "Kez",
    "imgName": "kez",
    "positions": [
      1,
      2
    ],
    "attr": "agi",
    "cx": 3,
    "tags": [
      "physical_right_click",
      "farm_scale",
      "magic_burst",
      "mobility",
      "physical_damage",
      "gap_close"
    ],
    "weakness": [
      "silence",
      "gap_close",
      "armor_reduction",
      "gank",
      "point_target_disable"
    ]
  }
];
